In [1]:
import pandas as pd
import fractions
import re
import string
import nltk
import spacy 
import numpy as np
import math
from tqdm import tqdm 

from spacy.matcher import Matcher
from spacy.tokens import Span
from spacy import displacy



data=pd.read_csv("df_product_test.csv")
data

Product  name  \
0                              Baby Trend Diaper Champ   333   
1                          BABYBJORN Potty Chair - Red   232   
2                     Philips Avent 3 Pack 9oz Bottles   191   
3                           Munchkin Mozart Magic Cube   191   
4                          PRIMO EuroBath, Pearl White   182   
..                                                 ...   ...   
356  Semanario (7) Little Girls 14k Gold Overlay Ba...     1   
357        Gerber Diaper Service Cloth Diapers (6-pk.)     1   
358  Large Jungle Animals (Panda, Lion, Elephant, G...     1   
359  Beautiful Girl and Black Flower Removable Viny...     1   
360              Playtex VentAire Bottle 6 oz. - 1 pk.     1   

                   Category  
0                 Diapering  
1                   Nursery  
2                 Baby_care  
3    Activity_entertainment  
4                   Nursery  
..                      ...  
356     Apparel_accessories  
357               Diapering  
358       Baby_toddler_toys  
359                 Nursery  
360               Baby_care  

[361 rows x 3 columns]

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split


from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [3]:
data_new = data.rename(columns={'total': 'name'}, index={'ONE': 'Row_1'})


In [4]:
data_new.head()


Product  name                Category
0           Baby Trend Diaper Champ   333               Diapering
1       BABYBJORN Potty Chair - Red   232                 Nursery
2  Philips Avent 3 Pack 9oz Bottles   191               Baby_care
3        Munchkin Mozart Magic Cube   191  Activity_entertainment
4       PRIMO EuroBath, Pearl White   182                 Nursery

In [5]:
import xgboost as xgb


In [6]:
count_vec=CountVectorizer()
bow=count_vec.fit_transform(data_new['Product'])
bow=np.array(bow.todense())

In [7]:
x=bow
y=data_new['Category']

In [8]:
y=pd.factorize(y)[0]
y

array([ 0,  1,  2,  3,  1,  4,  1,  1,  5,  6,  6,  0,  1,  4,  6,  7,  6,
        6,  6,  2,  1,  1,  6,  4,  6,  6,  6,  0,  5,  5,  8,  2,  1,  8,
        2,  2,  8,  6,  6,  9,  9,  9,  4,  6,  4,  3,  4,  0,  2,  9,  8,
        2,  6,  6,  0,  6,  9,  1,  6,  9,  6,  2,  4,  1,  2, 10,  4,  4,
        4,  4,  4,  2,  4,  4,  1,  8,  2,  4,  6,  9, 11,  6,  1,  4,  6,
        6,  4,  8,  4,  2,  1,  9,  4,  4,  4,  6,  2,  6,  6,  2, 12,  6,
        4,  6,  8,  4,  8,  8,  8,  2,  1,  6,  0,  0,  2,  6,  0,  2,  7,
        3,  6,  6, 10,  0,  1,  1,  6,  2,  6, 13,  6,  2,  4,  4,  8, 10,
        1,  8,  3,  0, 10,  4,  4,  4,  2, 11,  0,  9,  4, 11,  2,  2, 13,
        4, 10,  4,  8,  4,  4,  8,  8,  9,  6, 11,  0,  8,  6,  6,  1,  5,
        6,  2,  6,  2,  2, 13,  4,  6,  6,  2,  4,  6,  1,  4,  8,  2, 10,
        6,  6, 12,  2,  6, 10, 10,  1,  2,  8,  4,  1, 13, 13,  1,  6,  6,
        1,  6,  6,  2,  8,  0,  2,  2, 13,  4,  8,  8,  6,  6,  6, 10,  6,
        2, 10, 13,  1,  1

In [9]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=123)


In [52]:
from xgboost import XGBClassifier
from sklearn.linear_model import SGDClassifier

model = XGBClassifier(
    learning_rate =0.05,
 n_estimators=1000,
 max_depth=100,
 min_child_weight=1,
 gamma=0,
 subsample=0.8,
 colsample_bytree=0.8,
 objective= 'binary:logistic',
 nthread=4,
 scale_pos_weight=1,




)
# model=SGDClassifier(loss='modified_huber',shuffle=True,random_state=101)



In [53]:
model.fit(X_train, y_train)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[13:57:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:576: 
Parameters: { "scale_pos_weight" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[13:57:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8,
              enable_categorical=False, gamma=0, gpu_id=-1,
              importance_type=None, interaction_constraints='',
              learning_rate=0.05, max_delta_step=0, max_depth=100,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=1000, n_jobs=4, nthread=4, num_parallel_tree=1,
              objective='multi:softprob', predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.8,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [54]:
y_pred = model.predict(X_test)


In [55]:
y_pred


array([ 8,  1,  0,  1,  2,  1,  4,  8,  1,  0, 13,  1,  4,  6,  2,  2,  1,
        1,  8,  1,  8,  4,  2,  2,  2,  6,  8,  2,  4,  1,  8,  6,  6,  1,
       10,  8,  8, 11,  1,  1,  2,  2,  1,  8,  1,  1,  1,  8,  6,  1,  8,
        6,  6,  1,  2,  1,  8,  6,  1,  8,  8,  8,  8,  8,  1,  1,  2,  6,
        4,  8,  2,  6,  1,  1,  8,  6,  8,  8,  2,  1, 12, 12,  6,  1,  8,
        6,  8,  1,  1,  8,  8,  2,  8,  4,  1,  8,  2,  6,  8,  4,  4,  8,
        2,  1,  8,  8,  6,  6,  2])

In [56]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.46788990825688076

In [57]:
# data_dmatrix = xgb.DMatrix(data=x,label=y)


In [58]:
# params = {"objective":"reg:linear",'colsample_bytree': 0.3,'learning_rate': 0.1,
#                 'max_depth': 5, 'alpha': 10}

# cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
#                     num_boost_round=50,early_stopping_rounds=10,metrics="accuracy", as_pandas=True, seed=123)