In [1]:
import pandas as pd
doc=pd.read_csv("used4.5.csv")
doc

Unnamed: 0                                               name  \
0             0                           Planetwise Flannel Wipes   
1             1                              Planetwise Wipe Pouch   
2             2                Annas Dream Full Quilt with 2 Shams   
3             3  Stop Pacifier Sucking without tears with Thumb...   
4             4  Stop Pacifier Sucking without tears with Thumb...   
..          ...                                                ...   
408         654  U·nikaka Unisex Baby 0-48 Months 5-Pack Pants ...   
409         658  U·nikaka Unisex Baby 0-48 Months 5-Pack Pants ...   
410         660  HAICHEN TEC Ferret Clothes Turtleneck Sweater ...   
411         661  HAICHEN TEC Ferret Clothes Turtleneck Sweater ...   
412         663  HAICHEN TEC Ferret Clothes Turtleneck Sweater ...   

                                                review  index  \
0    These flannel wipes are OK, but in my opinion ...      0   
1    it came early and was not disappointed. i love...      1   
2    Very soft and comfortable and warmer than it l...      2   
3    This is a product well worth the purchase.  I ...      3   
4    All of my kids have cried non-stop when I trie...      4   
..                                                 ...    ...   
408  The sweaters are very nice and fit quite well....    654   
409  My 13 month old is short and round lol. So I’m...    658   
410  This is sp cute and hilarious 100 recomend goo...    660   
411  Mr. B is only 4 weeks old and looks so handsom...    661   
412  I wanted to dress up my guinea pig but the swe...    663   

                Category  
0              Baby_Care  
1              Diapering  
2                Nursery  
3              Baby_Care  
4              Baby_Care  
..                   ...  
408  Apparel_accessories  
409  Apparel_accessories  
410  Apparel_accessories  
411  Apparel_accessories  
412  Apparel_accessories  

[413 rows x 5 columns]

In [2]:
data_text=doc[["review","Category"]]
data_text['index']=data_text.index

documents=data_text

<ipython-input-2-318acfee2307>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_text['index']=data_text.index


In [3]:
documents

review             Category  \
0    These flannel wipes are OK, but in my opinion ...            Baby_Care   
1    it came early and was not disappointed. i love...            Diapering   
2    Very soft and comfortable and warmer than it l...              Nursery   
3    This is a product well worth the purchase.  I ...            Baby_Care   
4    All of my kids have cried non-stop when I trie...            Baby_Care   
..                                                 ...                  ...   
408  The sweaters are very nice and fit quite well....  Apparel_accessories   
409  My 13 month old is short and round lol. So I’m...  Apparel_accessories   
410  This is sp cute and hilarious 100 recomend goo...  Apparel_accessories   
411  Mr. B is only 4 weeks old and looks so handsom...  Apparel_accessories   
412  I wanted to dress up my guinea pig but the swe...  Apparel_accessories   

     index  
0        0  
1        1  
2        2  
3        3  
4        4  
..     ...  
408    408  
409    409  
410    410  
411    411  
412    412  

[413 rows x 3 columns]

In [4]:
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
import nltk.stem as stemmer
from nltk.stem.porter import *
import numpy as np
np.random.seed(2018)
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /Users/deth/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [5]:
stemmer=PorterStemmer()
def lemmatize_stemming(text):
      return stemmer.stem(WordNetLemmatizer().lemmatize(text,pos='v'))

def preprocess(text):
    result=[]
    for token in gensim.utils.simple_preprocess(text):
        if token not in gensim.parsing.preprocessing.STOPWORDS and len(token) >3:
              result.append(lemmatize_stemming(token))
  
    return result

In [6]:
doc_sample=documents[documents['index']==4].values[0][0]
print('original document')
words=[]
for word in doc_sample.split(' '):
      words.append(word)
print(words)
print('\n\n tokenized and lemmatized document: ')
print(preprocess(doc_sample))

original document
['All', 'of', 'my', 'kids', 'have', 'cried', 'non-stop', 'when', 'I', 'tried', 'to', 'ween', 'them', 'off', 'their', 'pacifier,', 'until', 'I', 'found', 'Thumbuddy', 'To', "Love's", 'Binky', 'Fairy', 'Puppet.', '', 'It', 'is', 'an', 'easy', 'way', 'to', 'work', 'with', 'your', 'kids', 'to', 'allow', 'them', 'to', 'understand', 'where', 'their', 'pacifier', 'is', 'going', 'and', 'help', 'them', 'part', 'from', 'it.This', 'is', 'a', 'must', 'buy', 'book,', 'and', 'a', 'great', 'gift', 'for', 'expecting', 'parents!!', '', 'You', 'will', 'save', 'them', 'soo', 'many', 'headaches.Thanks', 'for', 'this', 'book!', '', 'You', 'all', 'rock!!']


 tokenized and lemmatized document: 
['kid', 'cri', 'stop', 'tri', 'ween', 'pacifi', 'thumbuddi', 'love', 'binki', 'fairi', 'puppet', 'easi', 'work', 'kid', 'allow', 'understand', 'pacifi', 'go', 'help', 'book', 'great', 'gift', 'expect', 'parent', 'save', 'headach', 'thank', 'book', 'rock']


In [7]:
documents.dropna(subset = ["review"], inplace=True) # drop those rows which have NaN value cells


<ipython-input-7-00cd468fc166>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  documents.dropna(subset = ["review"], inplace=True) # drop those rows which have NaN value cells


In [8]:
processed_docs = documents['review'].map(preprocess)
processed_docs

0      [flannel, wipe, opinion, worth, keep, order, s...
1      [come, earli, disappoint, love, planet, wise, ...
2      [soft, comfort, warmer, look, size, perfectli,...
3      [product, worth, purchas, like, posit, ingeni,...
4      [kid, cri, stop, tri, ween, pacifi, thumbuddi,...
                             ...                        
408    [sweater, nice, ferret, mind, fabric, great, p...
409    [month, short, round, find, difficult, pant, p...
410    [cute, hilari, recomend, good, ador, halloween...
411    [week, look, handsom, littl, sweater, hard, sw...
412    [want, dress, guinea, sweater, small, especi, ...
Name: review, Length: 413, dtype: object

In [9]:
dictionary=gensim.corpora.Dictionary(processed_docs)
count=0

for k,v in dictionary.iteritems():
    print(k,v)
    count+=1
    if count>10:
        break

0 blue
1 boyfor
2 cloth
3 countwhich
4 face
5 flannel
6 hand
7 handl
8 higher
9 issu
10 keep


In [10]:
dictionary.filter_extremes(no_below=15,no_above=0.5)


In [11]:
bow_corpus=[dictionary.doc2bow(doc) for doc in processed_docs]
bow_corpus[4]


[(13, 1),
 (24, 2),
 (25, 1),
 (26, 1),
 (27, 1),
 (28, 1),
 (29, 1),
 (30, 1),
 (31, 2),
 (32, 1),
 (33, 1),
 (34, 1)]

In [12]:
bow_doc_4=bow_corpus[4]
for i in range(len(bow_doc_4)):
    print("Word {} (\"{}\") appears {} time.".format(bow_doc_4[i][0], 
                                               dictionary[bow_doc_4[i][0]], 
bow_doc_4[i][1]))

Word 13 ("love") appears 1 time.
Word 24 ("book") appears 2 time.
Word 25 ("easi") appears 1 time.
Word 26 ("expect") appears 1 time.
Word 27 ("gift") appears 1 time.
Word 28 ("go") appears 1 time.
Word 29 ("great") appears 1 time.
Word 30 ("help") appears 1 time.
Word 31 ("kid") appears 2 time.
Word 32 ("parent") appears 1 time.
Word 33 ("tri") appears 1 time.
Word 34 ("work") appears 1 time.


In [13]:
from gensim import corpora, models
tfidf=models.TfidfModel(bow_corpus)
corpus_tfidf=tfidf[bow_corpus]

from pprint import pprint

for doc in corpus_tfidf:
  pprint(doc)
  break

[(0, 0.37378287425890977),
 (1, 0.2910888830907095),
 (2, 0.32540999039054613),
 (3, 0.1454802833186967),
 (4, 0.2846385440521788),
 (5, 0.36733253522037906),
 (6, 0.36121313179202574),
 (7, 0.31688477799387366),
 (8, 0.28153961109325704),
 (9, 0.3498424166134522)]


In [14]:
lda_model=gensim.models.LdaMulticore(bow_corpus,num_topics=8,id2word=dictionary,passes=2,workers=2)

In [15]:

category=""
for idx, topic in lda_model.print_topics(-1):
        print('Topic:{}\nwords:{}\ncategory:{}\n'.format(idx,topic,category))
   
        
   
    
  

Topic:0
words:0.108*"babi" + 0.035*"great" + 0.034*"love" + 0.027*"time" + 0.026*"product" + 0.026*"month" + 0.023*"buy" + 0.023*"want" + 0.018*"like" + 0.017*"book"
category:

Topic:1
words:0.057*"sling" + 0.047*"monitor" + 0.044*"babi" + 0.043*"like" + 0.031*"month" + 0.028*"great" + 0.023*"easi" + 0.019*"good" + 0.018*"nice" + 0.018*"want"
category:

Topic:2
words:0.046*"love" + 0.045*"like" + 0.045*"month" + 0.040*"year" + 0.035*"babi" + 0.034*"look" + 0.026*"book" + 0.025*"littl" + 0.024*"buy" + 0.021*"daughter"
category:

Topic:3
words:0.060*"play" + 0.041*"great" + 0.031*"like" + 0.027*"camera" + 0.027*"love" + 0.027*"littl" + 0.024*"go" + 0.024*"turn" + 0.024*"help" + 0.022*"product"
category:

Topic:4
words:0.066*"love" + 0.061*"babi" + 0.029*"need" + 0.026*"camera" + 0.025*"easi" + 0.022*"recommend" + 0.021*"monitor" + 0.020*"month" + 0.019*"year" + 0.019*"littl"
category:

Topic:5
words:0.076*"book" + 0.044*"love" + 0.039*"qualiti" + 0.038*"babi" + 0.036*"play" + 0.032*"time

In [16]:
category=""

for index, score in sorted(lda_model[bow_corpus[4]],key=lambda tup:-1*tup[1]):
    
        print("\nScore:{}\t \nTopic:{}\nCategory:{}\n".format(score,lda_model.print_topic(index,10),category))
    


Score:0.5985352396965027	 
Topic:0.076*"book" + 0.044*"love" + 0.039*"qualiti" + 0.038*"babi" + 0.036*"play" + 0.032*"time" + 0.030*"like" + 0.029*"cute" + 0.027*"great" + 0.025*"color"
Category:


Score:0.351362407207489	 
Topic:0.060*"play" + 0.041*"great" + 0.031*"like" + 0.027*"camera" + 0.027*"love" + 0.027*"littl" + 0.024*"go" + 0.024*"turn" + 0.024*"help" + 0.022*"product"
Category:



In [17]:
lda_model_tfidf=gensim.models.LdaMulticore(corpus_tfidf,num_topics=8,id2word=dictionary,passes=2,workers=4)
for idx, topic in lda_model_tfidf.print_topics(-1):
      print('Topic: {} Word: {}'.format(idx,topic))

Topic: 0 Word: 0.035*"gift" + 0.031*"great" + 0.029*"play" + 0.025*"diaper" + 0.024*"size" + 0.023*"leav" + 0.022*"love" + 0.020*"turn" + 0.020*"product" + 0.020*"buy"
Topic: 1 Word: 0.048*"diaper" + 0.038*"book" + 0.037*"perfect" + 0.031*"babi" + 0.025*"tri" + 0.023*"expect" + 0.020*"look" + 0.019*"happi" + 0.018*"page" + 0.017*"right"
Topic: 2 Word: 0.027*"cute" + 0.027*"qualiti" + 0.026*"camera" + 0.025*"babi" + 0.024*"monitor" + 0.020*"think" + 0.019*"interact" + 0.019*"good" + 0.018*"year" + 0.018*"month"
Topic: 3 Word: 0.027*"love" + 0.025*"friend" + 0.023*"toy" + 0.023*"daughter" + 0.023*"play" + 0.022*"think" + 0.021*"babi" + 0.021*"year" + 0.020*"recommend" + 0.019*"month"
Topic: 4 Word: 0.034*"book" + 0.026*"item" + 0.023*"time" + 0.022*"price" + 0.020*"babi" + 0.020*"buy" + 0.019*"play" + 0.019*"read" + 0.018*"like" + 0.017*"famili"
Topic: 5 Word: 0.038*"vibrat" + 0.034*"like" + 0.030*"teether" + 0.027*"easi" + 0.025*"littl" + 0.024*"love" + 0.024*"hold" + 0.020*"month" + 0.

In [18]:
for index, score in sorted(lda_model_tfidf[bow_corpus[4]],key=lambda tup:-1*tup[1]):
  print("\nScore:{}\t \nTopic:{}".format(score,lda_model.print_topic(index,10)))


Score:0.581971287727356	 
Topic:0.057*"sling" + 0.047*"monitor" + 0.044*"babi" + 0.043*"like" + 0.031*"month" + 0.028*"great" + 0.023*"easi" + 0.019*"good" + 0.018*"nice" + 0.018*"want"

Score:0.3679336607456207	 
Topic:0.056*"book" + 0.042*"month" + 0.038*"diaper" + 0.035*"love" + 0.035*"babi" + 0.033*"think" + 0.025*"soft" + 0.022*"perfect" + 0.022*"daughter" + 0.019*"start"


In [19]:
import pyLDAvis
import pyLDAvis.gensim_models
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim_models.prepare(lda_model, bow_corpus, dictionary)
vis

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
1     -0.098769  0.039788       1        1  17.250119
2      0.029647 -0.031093       2        1  14.600619
0     -0.039499  0.003236       3        1  14.516085
4     -0.052504  0.010480       4        1  14.417479
6      0.061083 -0.046933       5        1  13.984668
3     -0.061861  0.033838       6        1  10.646332
7      0.136522  0.096511       7        1   8.516064
5      0.025381 -0.105827       8        1   6.068634, topic_info=       Term        Freq       Total Category  logprob  loglift
24     book  111.000000  111.000000  Default  30.0000  30.0000
46   diaper   93.000000   93.000000  Default  29.0000  29.0000
65     play   86.000000   86.000000  Default  28.0000  28.0000
135   sling   70.000000   70.000000  Default  27.0000  27.0000
44     babi  258.000000  258.000000  Default  26.0000  26.0000
..      ...         ...         ...      ...      ...      ...
91     hard    3.336770   39.044183   Topic8  -4.6208   0.3423
1      hand    3.391801   41.639773   Topic8  -4.6044   0.2943
113  differ    3.364161   50.352168   Topic8  -4.6126   0.0962
46   diaper    4.224446   93.721625   Topic8  -4.3849  -0.2974
56    think    3.767428   84.823704   Topic8  -4.4994  -0.3121

[366 rows x 6 columns], token_table=      Topic      Freq  Term
term                       
41        1  0.459815   abl
41        2  0.108192   abl
41        3  0.108192   abl
41        4  0.135240   abl
41        5  0.135240   abl
...     ...       ...   ...
89        3  0.055427  year
89        4  0.221709  year
89        5  0.152425  year
89        6  0.013857  year
89        8  0.083141  year

[942 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[2, 3, 1, 5, 7, 4, 8, 6])

In [20]:
unseen_document = 'This wallpaper has always been one of my favorite  '
bow_vector = dictionary.doc2bow(preprocess(unseen_document))
for index, score in sorted(lda_model[bow_vector], key=lambda tup: -1*tup[1]):
    
        print("\nScore:{}\t \nTopic:{}\nCategory:{}\n".format(score,lda_model.print_topic(index,5),category))
  


Score:0.5620099902153015	 
Topic:0.076*"book" + 0.044*"love" + 0.039*"qualiti" + 0.038*"babi" + 0.036*"play"
Category:


Score:0.06265942752361298	 
Topic:0.060*"play" + 0.041*"great" + 0.031*"like" + 0.027*"camera" + 0.027*"love"
Category:


Score:0.0626063346862793	 
Topic:0.108*"babi" + 0.035*"great" + 0.034*"love" + 0.027*"time" + 0.026*"product"
Category:


Score:0.06259351968765259	 
Topic:0.056*"book" + 0.042*"month" + 0.038*"diaper" + 0.035*"love" + 0.035*"babi"
Category:


Score:0.06255311518907547	 
Topic:0.046*"love" + 0.045*"like" + 0.045*"month" + 0.040*"year" + 0.035*"babi"
Category:


Score:0.06255277991294861	 
Topic:0.073*"diaper" + 0.041*"daughter" + 0.038*"great" + 0.037*"love" + 0.029*"hold"
Category:


Score:0.06251531839370728	 
Topic:0.057*"sling" + 0.047*"monitor" + 0.044*"babi" + 0.043*"like" + 0.031*"month"
Category:


Score:0.06250954419374466	 
Topic:0.066*"love" + 0.061*"babi" + 0.029*"need" + 0.026*"camera" + 0.025*"easi"
Category:



/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [21]:
unseen_document = 'This wallpaper has always been one of my favorite  '
bow_vector = dictionary.doc2bow(preprocess(unseen_document))
for index, score in sorted(lda_model_tfidf[bow_vector], key=lambda tup: -1*tup[1]):
    
        print("\nScore:{}\t \nTopic:{}\nCategory:{}\n".format(score,lda_model.print_topic(index,5),category))
  


Score:0.5622456073760986	 
Topic:0.060*"play" + 0.041*"great" + 0.031*"like" + 0.027*"camera" + 0.027*"love"
Category:


Score:0.06265490502119064	 
Topic:0.066*"love" + 0.061*"babi" + 0.029*"need" + 0.026*"camera" + 0.025*"easi"
Category:


Score:0.06255194544792175	 
Topic:0.057*"sling" + 0.047*"monitor" + 0.044*"babi" + 0.043*"like" + 0.031*"month"
Category:


Score:0.0625176951289177	 
Topic:0.046*"love" + 0.045*"like" + 0.045*"month" + 0.040*"year" + 0.035*"babi"
Category:


Score:0.06251467019319534	 
Topic:0.073*"diaper" + 0.041*"daughter" + 0.038*"great" + 0.037*"love" + 0.029*"hold"
Category:


Score:0.06251347064971924	 
Topic:0.056*"book" + 0.042*"month" + 0.038*"diaper" + 0.035*"love" + 0.035*"babi"
Category:


Score:0.06250110268592834	 
Topic:0.108*"babi" + 0.035*"great" + 0.034*"love" + 0.027*"time" + 0.026*"product"
Category:


Score:0.06250057369470596	 
Topic:0.076*"book" + 0.044*"love" + 0.039*"qualiti" + 0.038*"babi" + 0.036*"play"
Category:



/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [22]:
def format_topic_sentences(lda_model=lda_model_tfidf, corpus=bow_corpus, texts=processed_docs):
    sent_topics_df=pd.DataFrame()
    
    for i, row_list in enumerate(lda_model[corpus]):
        row=row_list[0] if lda_model.per_word_topics else row_list
        row=sorted(row,key=lambda x:(x[1]),reverse=True)
        
        for j, (topic_num,prop_topic) in enumerate(row):
            if j==0:
                wp=lda_model.show_topic(topic_num)
                topic_keywords=', '.join([word for word, prop in wp])
                sent_topics_df=sent_topics_df.append(pd.Series([int(topic_num),round(prop_topic,4),topic_keywords]),ignore_index=True)
            else:
                break
    sent_topics_df.columns=['Dominant_topic','Perc_contribution','Topic_keywords']
    contents=pd.Series(texts)
    sent_topics_df=pd.concat([sent_topics_df,contents],axis=1)
    return sent_topics_df

df_topic_sents_keywords = format_topic_sentences(lda_model=lda_model, corpus=bow_corpus, texts=processed_docs)

# Format.  
df_dominant_topic = df_topic_sents_keywords.reset_index()
df_dominant_topic.columns = ['Document_No', 'Dominant_Topic', 'Topic_Perc_Contrib', 'Keywords', 'Text']
df_dominant_topic['index']=df_dominant_topic.index
df_dominant_topic



/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Document_No  Dominant_Topic  Topic_Perc_Contrib  \
0              0             4.0              0.9203   
1              1             4.0              0.8540   
2              2             6.0              0.8539   
3              3             0.0              0.3455   
4              4             5.0              0.5985   
..           ...             ...                 ...   
408          408             6.0              0.9026   
409          409             6.0              0.9203   
410          410             5.0              0.8248   
411          411             6.0              0.5791   
412          412             1.0              0.8247   

                                              Keywords  \
0    love, babi, need, camera, easi, recommend, mon...   
1    love, babi, need, camera, easi, recommend, mon...   
2    book, month, diaper, love, babi, think, soft, ...   
3    babi, great, love, time, product, month, buy, ...   
4    book, love, qualiti, babi, play, time, like, c...   
..                                                 ...   
408  book, month, diaper, love, babi, think, soft, ...   
409  book, month, diaper, love, babi, think, soft, ...   
410  book, love, qualiti, babi, play, time, like, c...   
411  book, month, diaper, love, babi, think, soft, ...   
412  sling, monitor, babi, like, month, great, easi...   

                                                  Text  index  
0    [flannel, wipe, opinion, worth, keep, order, s...      0  
1    [come, earli, disappoint, love, planet, wise, ...      1  
2    [soft, comfort, warmer, look, size, perfectli,...      2  
3    [product, worth, purchas, like, posit, ingeni,...      3  
4    [kid, cri, stop, tri, ween, pacifi, thumbuddi,...      4  
..                                                 ...    ...  
408  [sweater, nice, ferret, mind, fabric, great, p...    408  
409  [month, short, round, find, difficult, pant, p...    409  
410  [cute, hilari, recomend, good, ador, halloween...    410  
411  [week, look, handsom, littl, sweater, hard, sw...    411  
412  [want, dress, guinea, sweater, small, especi, ...    412  

[413 rows x 6 columns]

In [23]:
data=df_dominant_topic['Dominant_Topic']
new_category=[]
category=""
for i in data:
    if i == 0:
        category="Baby_care"
        new_category.append(category)
    if i==1:
        category="Nursery"
        new_category.append(category)
    if i==2:
        category="Baby_stationary"
        new_category.append(category)
    if i==3:
        category="Diapering"
        new_category.append(category)
    if i==4:
        category="Activity_entertainment"
        new_category.append(category)
    if i==5:
        category="Gift"
        new_category.append(category)
    if i==6:
        category="Apparel_accessories"
        new_category.append(category)
    if i==7:
        category="Baby_toddler_toy"
        new_category.append(category)

new_category

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


['Activity_entertainment',
 'Activity_entertainment',
 'Apparel_accessories',
 'Baby_care',
 'Gift',
 'Diapering',
 'Apparel_accessories',
 'Baby_care',
 'Apparel_accessories',
 'Activity_entertainment',
 'Baby_care',
 'Apparel_accessories',
 'Baby_care',
 'Baby_care',
 'Nursery',
 'Baby_stationary',
 'Baby_stationary',
 'Activity_entertainment',
 'Baby_stationary',
 'Baby_care',
 'Baby_stationary',
 'Baby_stationary',
 'Apparel_accessories',
 'Baby_stationary',
 'Activity_entertainment',
 'Baby_stationary',
 'Baby_care',
 'Baby_stationary',
 'Apparel_accessories',
 'Gift',
 'Activity_entertainment',
 'Gift',
 'Baby_stationary',
 'Apparel_accessories',
 'Gift',
 'Apparel_accessories',
 'Gift',
 'Baby_stationary',
 'Gift',
 'Apparel_accessories',
 'Activity_entertainment',
 'Baby_stationary',
 'Gift',
 'Apparel_accessories',
 'Apparel_accessories',
 'Apparel_accessories',
 'Gift',
 'Baby_care',
 'Baby_care',
 'Apparel_accessories',
 'Baby_stationary',
 'Baby_stationary',
 'Gift',
 'Baby

In [24]:
new_category_col = pd.DataFrame({'col':new_category})
new_category_col['index']=new_category_col.index


new_category_col

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


col  index
0    Activity_entertainment      0
1    Activity_entertainment      1
2       Apparel_accessories      2
3                 Baby_care      3
4                      Gift      4
..                      ...    ...
408     Apparel_accessories    408
409     Apparel_accessories    409
410                    Gift    410
411     Apparel_accessories    411
412                 Nursery    412

[413 rows x 2 columns]

In [25]:
new_df_1 = pd.merge(df_dominant_topic, documents[['Category','index','review']], on='index')

new_df_1

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Document_No  Dominant_Topic  Topic_Perc_Contrib  \
0              0             4.0              0.9203   
1              1             4.0              0.8540   
2              2             6.0              0.8539   
3              3             0.0              0.3455   
4              4             5.0              0.5985   
..           ...             ...                 ...   
408          408             6.0              0.9026   
409          409             6.0              0.9203   
410          410             5.0              0.8248   
411          411             6.0              0.5791   
412          412             1.0              0.8247   

                                              Keywords  \
0    love, babi, need, camera, easi, recommend, mon...   
1    love, babi, need, camera, easi, recommend, mon...   
2    book, month, diaper, love, babi, think, soft, ...   
3    babi, great, love, time, product, month, buy, ...   
4    book, love, qualiti, babi, play, time, like, c...   
..                                                 ...   
408  book, month, diaper, love, babi, think, soft, ...   
409  book, month, diaper, love, babi, think, soft, ...   
410  book, love, qualiti, babi, play, time, like, c...   
411  book, month, diaper, love, babi, think, soft, ...   
412  sling, monitor, babi, like, month, great, easi...   

                                                  Text  index  \
0    [flannel, wipe, opinion, worth, keep, order, s...      0   
1    [come, earli, disappoint, love, planet, wise, ...      1   
2    [soft, comfort, warmer, look, size, perfectli,...      2   
3    [product, worth, purchas, like, posit, ingeni,...      3   
4    [kid, cri, stop, tri, ween, pacifi, thumbuddi,...      4   
..                                                 ...    ...   
408  [sweater, nice, ferret, mind, fabric, great, p...    408   
409  [month, short, round, find, difficult, pant, p...    409   
410  [cute, hilari, recomend, good, ador, halloween...    410   
411  [week, look, handsom, littl, sweater, hard, sw...    411   
412  [want, dress, guinea, sweater, small, especi, ...    412   

                Category                                             review  
0              Baby_Care  These flannel wipes are OK, but in my opinion ...  
1              Diapering  it came early and was not disappointed. i love...  
2                Nursery  Very soft and comfortable and warmer than it l...  
3              Baby_Care  This is a product well worth the purchase.  I ...  
4              Baby_Care  All of my kids have cried non-stop when I trie...  
..                   ...                                                ...  
408  Apparel_accessories  The sweaters are very nice and fit quite well....  
409  Apparel_accessories  My 13 month old is short and round lol. So I’m...  
410  Apparel_accessories  This is sp cute and hilarious 100 recomend goo...  
411  Apparel_accessories  Mr. B is only 4 weeks old and looks so handsom...  
412  Apparel_accessories  I wanted to dress up my guinea pig but the swe...  

[413 rows x 8 columns]

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split


from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
count_vec=CountVectorizer()
bow=count_vec.fit_transform(new_df_1['Keywords'].astype(str))
bow=np.array(bow.todense())
bow1=count_vec.fit_transform(new_df_1['Text'].astype(str))
bow1=np.array(bow1.todense())
bow2=np.concatenate((bow,bow1),axis=1)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [27]:
x=bow2
y=new_df_1['Category']

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [28]:
y1 = y.sample(frac=1).reset_index(drop=True)
y1

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0                        Gift
1           Baby_toddler_toys
2                   Baby_Care
3           Baby_toddler_toys
4      Activity_entertainment
                ...          
408                 Baby_Care
409                      Gift
410         Baby_toddler_toys
411       Apparel_accessories
412           Baby_stationary
Name: Category, Length: 413, dtype: object

In [29]:
x

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [30]:
x.shape

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(413, 2180)

In [31]:
y

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0                Baby_Care
1                Diapering
2                  Nursery
3                Baby_Care
4                Baby_Care
              ...         
408    Apparel_accessories
409    Apparel_accessories
410    Apparel_accessories
411    Apparel_accessories
412    Apparel_accessories
Name: Category, Length: 413, dtype: object

In [32]:
y.shape

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(413,)

In [33]:
# X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y)
# X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [34]:
# !pip3 install keras
# !pip3 install tensorflow

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [35]:
# !pip3 install tensorflow

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [36]:
# !pip3 install imbalanced-learn

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [37]:
# !pip install -U imbalanced-learn


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [38]:
# !pip3 install sklearn --upgrade

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [39]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.1,stratify=y)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [40]:
# SMOTE only use with training data. 
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

import imblearn

smt = SMOTE("minority")
# smt = RandomUnderSampler(random_state=42)
# smt=SMOTE()
X_SMOTE,y_SMOTE = smt.fit_resample(X_train, y_train)

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/Users/deth/opt/anaconda3/lib/python3.8/site-packages/imblearn/utils/_validation.py:586: FutureWarning: Pass sampling_strategy=minority as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [41]:
X_SMOTE.shape

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(430, 2180)

In [42]:
y_SMOTE.shape

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(430,)

In [43]:
# X_train,X_test,y_train,y_test=train_test_split(X_SMOTE,y_SMOTE,test_size=0.2,stratify=y_SMOTE)
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y)

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [44]:
len(X_train)

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


330

In [45]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
def evaluate_model(X_train, y_train, model):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    scores = cross_val_score(model, X_train, y_train, cv=3, scoring="accuracy")
    diff = scores.mean() - model.score(X_test, y_test)
    SD = diff / scores.std()
    
    print(f"Training Score:{model.score(X_train, y_train)}")
    print(f"Cross V Score: {scores.mean()} +/- {scores.std()}")
    print(f"Testing Score: {model.score(X_test, y_test)}")
    print(f"Cross & Test Diff: {diff}")
    print(f"Standard Deviations Away: {SD}")
    print(confusion_matrix(y_test, preds))

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [46]:
from sklearn import svm
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.ensemble import GradientBoostingClassifier



# model=svm.SVC(kernel='linear', C=1, random_state=0).fit(X_train,y_train) #0.54
model = LogisticRegression()#0.61

# # fit the model with data
# model.fit(X_train,y_train)
from sklearn.neighbors import KNeighborsClassifier

# model = KNeighborsClassifier(n_neighbors=3)#0.42

# # Train the model using the training sets
# model.fit(X_train,y_train)

# from sklearn.ensemble import RandomForestClassifier
# from keras.models import Sequential

# # Import `Dense` from `keras.layers`
# from keras.layers import Dense

# from keras.models import Sequential

# # Import `Dense` from `keras.layers`
# from keras.layers import Dense

# # Initialize the constructor
# model = Sequential()

# # Add an input layer 
# model.add(Dense(12, activation='relu', input_shape=(298, 1721)))

# # Add one hidden layer 
# model.add(Dense(8, activation='relu'))

# # Add an output layer 
# model.add(Dense(1, activation='sigmoid'))

# # #Create a Gaussian Classifier
# model=XGBClassifier(
# learning_rate =0.05,
#  n_estimators=1000,
#  max_depth=10,
#  min_child_weight=1,
#  gamma=0,
#  subsample=0.9,
#  colsample_bytree=0.9,
#  objective= 'multi:softmax',
#  nthread=10,
#  scale_pos_weight=1
# )
# model=RandomForestClassifier(n_estimators=100)#0.55
# model = GradientBoostingClassifier(n_estimators=20, learning_rate=0.5, max_features=2, max_depth=2, random_state=0)
# model = Sequential()

# # Add an input layer 
# model.add(Dense(12, activation='relu', input_shape=(1721,)))

# # Add one hidden layer 
# model.add(Dense(8, activation='relu'))

# # Add an output layer 
# model.add(Dense(1, activation='sigmoid'))
# model.compile(loss='binary_crossentropy',
#               optimizer='adam',
#               metrics=['accuracy'])



# #0.53 without parameter tuning
#when tuning with max_depth=10,subsample=0.9,colsample_bytree=0.8 or 0.9 increase to 0.56

# #Train the model using the training sets y_pred=clf.predict(X_test)
# model.fit(X_train,y_train)

from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
# model = GaussianNB()
# model = DecisionTreeClassifier()#0.47
# model.compile(loss='binary_crossentropy',
#               optimizer='adam',
#               metrics=['accuracy'])
# x1 = X_train.flatten()
                
# model.fit(x1, y_train,epochs=20, batch_size=1, verbose=1)

# Train Decision Tree Classifer

# with GaussinNB, 0.63

# Train the model using the training sets
model.fit(X_SMOTE,y_SMOTE)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


LogisticRegression()

In [47]:
y_pred=model.predict(X_test)
x1=accuracy_score(y_test,y_pred)
x1

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0.963855421686747

In [48]:
# import matplotlib.pyplot as plt
# plt.plot(y_test,y_pred)
# plt.show()

evaluate_model(X_SMOTE, y_SMOTE, model)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Training Score:0.9976744186046511
Cross V Score: 0.66749222999223 +/- 0.04817723009079589
Testing Score: 0.963855421686747
Cross & Test Diff: -0.29636319169451697
Standard Deviations Away: -6.1515199428440415
[[ 7  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0]
 [ 0  0  0 10  0  0  1  0]
 [ 0  0  1  0 16  0  0  0]
 [ 0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  9  0]
 [ 1  0  0  0  0  0  0 11]]


In [49]:
from imblearn.pipeline import make_pipeline

pipeline = make_pipeline(smt, model)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [50]:
evaluate_model(X_SMOTE, y_SMOTE, pipeline)


/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Training Score:0.9976744186046511
Cross V Score: 0.6698232323232323 +/- 0.04606070051499384
Testing Score: 0.963855421686747
Cross & Test Diff: -0.2940321893635147
Standard Deviations Away: -6.383580494347894
[[ 7  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0]
 [ 0  0  0 10  0  0  1  0]
 [ 0  0  1  0 16  0  0  0]
 [ 0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  9  0]
 [ 1  0  0  0  0  0  0 11]]


In [51]:
print(classification_report(y_test, y_pred))


                        precision    recall  f1-score   support

Activity_entertainment       0.88      1.00      0.93         7
   Apparel_accessories       1.00      1.00      1.00         4
             Baby_Care       0.94      1.00      0.97        17
       Baby_stationary       1.00      0.91      0.95        11
     Baby_toddler_toys       1.00      0.94      0.97        17
             Diapering       1.00      1.00      1.00         6
                  Gift       0.90      1.00      0.95         9
               Nursery       1.00      0.92      0.96        12

              accuracy                           0.96        83
             macro avg       0.96      0.97      0.97        83
          weighted avg       0.97      0.96      0.96        83



/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [52]:
# results, names = list(), list()
# for name, mode in model.items():
# # evaluate the model and collect the scores
#     scores = evaluate_model(X_SMOTE, y_SMOTE, pipeline)

# # store the results
#     results.append(scores)
#     names.append(name)
# # summarize progress along the way
#     print('>%s %.3f (%.3f)' % (name, mean(scores), std(scores)))
# # plot model performance for comparison
# pyplot.boxplot(results, labels=names, showmeans=True)
# pyplot.show()

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [53]:
results = pd.DataFrame(data={'predicted': y_pred, 'actual': y_test})
results['result'] = np.where(results['predicted']==results['actual'], 1, 0)
results.sort_values(by='result').head(20)

/Users/deth/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


predicted                  actual  result
65   Activity_entertainment                 Nursery       0
39                     Gift         Baby_stationary       0
226               Baby_Care       Baby_toddler_toys       0
395  Activity_entertainment  Activity_entertainment       1
329                    Gift                    Gift       1
154       Baby_toddler_toys       Baby_toddler_toys       1
171       Baby_toddler_toys       Baby_toddler_toys       1
211         Baby_stationary         Baby_stationary       1
33   Activity_entertainment  Activity_entertainment       1
396  Activity_entertainment  Activity_entertainment       1
363               Diapering               Diapering       1
68                  Nursery                 Nursery       1
376  Activity_entertainment  Activity_entertainment       1
255               Baby_Care               Baby_Care       1
347                 Nursery                 Nursery       1
264               Baby_Care               Baby_Care       1
205       Baby_toddler_toys       Baby_toddler_toys       1
163       Baby_toddler_toys       Baby_toddler_toys       1
258               Baby_Care               Baby_Care       1
379  Activity_entertainment  Activity_entertainment       1