In [1]:
import pandas as pd
df = pd.read_csv("amazon_baby.csv")
df

name  \
0                                Planetwise Flannel Wipes   
1                                   Planetwise Wipe Pouch   
2                     Annas Dream Full Quilt with 2 Shams   
3       Stop Pacifier Sucking without tears with Thumb...   
4       Stop Pacifier Sucking without tears with Thumb...   
...                                                   ...   
183526  Baby Teething Necklace for Mom Pretty Donut Sh...   
183527  Baby Teething Necklace for Mom Pretty Donut Sh...   
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)   
183529  Baby Food Freezer Tray - Bacteria Resistant, B...   
183530  Best 2 Pack Baby Car Shade for Kids - Window S...   

                                                   review  rating  
0       These flannel wipes are OK, but in my opinion ...       3  
1       it came early and was not disappointed. i love...       5  
2       Very soft and comfortable and warmer than it l...       5  
3       This is a product well worth the purchase.  I ...       5  
4       All of my kids have cried non-stop when I trie...       5  
...                                                   ...     ...  
183526  Such a great idea! very handy to have and look...       5  
183527  This product rocks!  It is a great blend of fu...       5  
183528  This item looks great and cool for my kids.......       5  
183529  I am extremely happy with this product. I have...       5  
183530  I love this product very mush . I have bought ...       5  

[183531 rows x 3 columns]

In [2]:
df.isnull().any()



name       True
review     True
rating    False
dtype: bool

In [3]:
df.isnull().sum()

name      318
review    829
rating      0
dtype: int64

In [4]:
df.isnull().sum().sum()

1147

In [5]:
df.shape


(183531, 3)

In [6]:
df=df.dropna()


In [7]:
import numpy as np
np.random.seed(34)
df1=df.sample(frac=0.3)

df1['Sentiments']=df1.rating.apply(lambda x: 0 if x in [1,2] else 1)



In [8]:
df1

name  \
165191  aden + anais Rayon From Bamboo Crib Sheet, Azu...   
108775  Hand Held Scalp Head Massager - Set of Three (...   
162820             Clevamama ClevaFoam Baby Pillow, Cream   
148217  Kids Line Velour Changing Pad Cover, Pirate Party   
46428                      Angel Dear Blankie, Green Frog   
...                                                   ...   
137608  Trend Lab CribWrap Fleece Rail Cover for Long ...   
156932     Babysight Digital Handheld Color Video Monitor   
171309                    Ecosusi Diaper Backpack, (pink)   
57598   North American Bear Pastel Pancake Bear Plush ...   
99994   Summer Infant Snuzzler Velboa for Head and Bod...   

                                                   review  rating  Sentiments  
165191  An off-white or cream sheet that is so soft. I...       5           1  
108775  I was skeptical about how well these will work...       5           1  
162820  It soft and material appears to be excellent. ...       5           1  
148217  This is a very nice cover. I have two because ...       5           1  
46428   I love these Lovies. They are cute, soft and d...       5           1  
...                                                   ...     ...         ...  
137608  Fit my Jenny Lind crib perfectly. Water proof ...       5           1  
156932  I purchased this and returned it immediately b...       1           0  
171309  I love this diaper bag. Everywhere I go with m...       5           1  
57598   This is Pancake Bear number 4 for our house.  ...       5           1  
99994   The Snuzzler is perfect for my baby boy. It ma...       5           1  

[54715 rows x 4 columns]

In [9]:
X=df.iloc[:,[1,2]].values
y=df.iloc[:,-1].values
X

array([['These flannel wipes are OK, but in my opinion not worth keeping.  I also ordered someImse Vimse Cloth Wipes-Ocean Blue-12 countwhich are larger, had a nicer, softer texture and just seemed higher quality.  I use cloth wipes for hands and faces and have been usingThirsties 6 Pack Fab Wipes, Boyfor about 8 months now and need to replace them because they are starting to get rough and have had stink issues for a while that stripping no longer handles.',
        3],
       ['it came early and was not disappointed. i love planet wise bags and now my wipe holder. it keps my osocozy wipes moist and does not leak. highly recommend it.',
        5],
       ['Very soft and comfortable and warmer than it looks...fit the full size bed perfectly...would recommend to anyone looking for this type of quilt',
        5],
       ...,
       ['This item looks great and cool for my kids....I know this Company and its great in quality...',
        5],
       ['I am extremely happy with this produc

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])
X

array([[125029, 3],
       [175943, 5],
       [154407, 5],
       ...,
       [142190, 5],
       [23850, 5],
       [52817, 5]], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)


In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


In [13]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)


GaussianNB()

In [14]:
y_pred=classifier.predict(X_test)
y_pred

array([1, 5, 2, ..., 5, 2, 5])

In [15]:
y_test

array([1, 5, 2, ..., 5, 2, 5])

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)
ac

1.0